
#Disables certain types. Note that all these configs, like in any other mod, only hide stuff from tabs and disable their recipes
[types]

	[types.leaves_type]

		[types.leaves_type.quark]
			ancient = true
			blue_blossom = true
			lavender_blossom = true
			orange_blossom = true
			yellow_blossom = true
			red_blossom = true

		[types.leaves_type.northstar]
			coiler = true
			argyre = true
			wilter = true

		[types.leaves_type.aether]
			skyroot = true
			golden_oak = true
			crystal = true
			crystal_fruit = true
			holiday = true
			decorated_holiday = true

		[types.leaves_type.deep_aether]
			roseroot = true
			flowering_roseroot = true
			blue_roseroot = true
			flowering_blue_roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.leaves_type.ancient_aether]
			crystal_skyroot = true
			enchanted_skyroot = true
			skyroot_pine = true
			blue_skyroot_pine = true
			highsproot = true
			sakura = true

		[types.leaves_type.aether_redux]
			blightwillow = true
			glacia = true
			purple_glacia = true
			gilded_oak = true
			blighted_skyroot = true

		[types.leaves_type.betternether]
			willow = true
			rubeus = true
			anchor_tree = true
			nether_sakura = true

		[types.leaves_type.betterend]
			pythadendron = true
			lacugrove = true
			dragon_tree = true
			tenanea = true
			lucernia = true

	[types.cake]

		[types.cake.tfc]
			cake = true

		[types.cake.createaddition]
			chocolate_cake = true
			honey_cake = true

	[types.wood_type]

		[types.wood_type.quark]
			azalea = true
			ancient = true
			blossom = true

		[types.wood_type.botania]
			livingwood = true
			dreamwood = true

		[types.wood_type.tfc]
			acacia = true
			ash = true
			aspen = true
			birch = true
			blackwood = true
			chestnut = true
			douglas_fir = true
			hickory = true
			kapok = true
			mangrove = true
			maple = true
			oak = true
			palm = true
			pine = true
			rosewood = true
			sequoia = true
			spruce = true
			sycamore = true
			white_cedar = true
			willow = true

		[types.wood_type.afc]
			baobab = true
			eucalyptus = true
			mahogany = true
			hevea = true
			tualang = true
			teak = true
			cypress = true
			fig = true
			ironwood = true
			ipe = true

		[types.wood_type.iceandfire]
			dreadwood = true

		[types.wood_type.northstar]
			coiler = true
			wilter = true
			argyre = true
			calorian = true

		[types.wood_type.createdieselgenerators]
			chip_wood = true

		[types.wood_type.aether]
			skyroot = true

		[types.wood_type.deep_aether]
			roseroot = true
			yagroot = true
			cruderoot = true
			conberry = true
			sunroot = true

		[types.wood_type.ancient_aether]
			highsproot = true
			sakura = true

		[types.wood_type.aether_redux]
			fieldsproot = true
			blightwillow = true
			cloudcap = true
			jellyshroom = true
			crystal = true
			glacia = true

		[types.wood_type.betternether]
			nether_reed = true
			stalagnate = true
			willow = true
			wart = true
			rubeus = true
			mushroom_fir = true
			nether_mushroom = true
			anchor_tree = true
			nether_sakura = true

		[types.wood_type.betterend]
			mossy_glowshroom = true
			pythadendron = true
			end_lotus = true
			lacugrove = true
			dragon_tree = true
			tenanea = true
			helix_tree = true
			umbrella_tree = true
			jellyshroom = true
			lucernia = true

	[types.stone_type]

		[types.stone_type.botania]
			livingrock = true

		[types.stone_type.northstar]
			mars_stone = true
			moon_stone = true
			venus_stone = true
			mercury_stone = true

		[types.stone_type.aetherworks]
			suevite = true

		[types.stone_type.aether]
			holystone = true

		[types.stone_type.deep_aether]
			aseterite = true
			aether_mud = true

		[types.stone_type.aether_redux]
			sentrite = true

		[types.stone_type.iceandfire]
			dread_stone = true

		[types.stone_type.absentbydesign]
			wall_quartz = true
			gate_stone = true
			gate_blackstone = true
			trapdoor_stone = true
			trapdoor_blackstone = true
			trapdoor_quartz = true

		[types.stone_type.create]
			cut_granite = true
			cut_diorite = true
			cut_andesite = true
			cut_calcite = true
			cut_dripstone = true
			cut_deepslate = true
			cut_tuff = true
			cut_asurine = true
			cut_crimsite = true
			cut_limestone = true
			cut_ochrum = true
			cut_scoria = true
			cut_scorchia = true
			cut_veridium = true

		[types.stone_type.tfmg]
			cut_bauxite = true
			cut_galena = true

		[types.stone_type.quark]
			soul_sandstone = true
			permafrost = true
			limestone = true
			jasper = true
			shale = true
			myalite = true

		[types.stone_type.supplementaries]
			ash = true

		[types.stone_type.betternether]
			blue_obsidian = true

		[types.stone_type.betterend]
			flavolite = true
			violecite = true
			sulphuric_rock = true
			virid_jadestone = true
			azure_jadestone = true
			sandy_jadestone = true
			umbralith = true
			smaragdant_crystal = true

#Disables specific entries
[entries]

	[entries.leaves_type]

		[entries.leaves_type.quark]
			hedge = true
			leaf_carpet = true

		[entries.leaves_type.mcwfences]
			hedge = true

	[entries.wood_type]

		[entries.wood_type.quark]
			vertical_planks = true
			ladder = true
			post = true
			trapped_chest = true
			chest = true
			hollow_log = true
			bookshelf = true
			stripped_post = true

		[entries.wood_type.farmersdelight]
			cabinet = true

		[entries.wood_type.create]
			window_pane = true
			window = true

		[entries.wood_type.mcwroofs]
			planks_upper_steep_roof = true
			top_roof = true
			lower_roof = true
			planks_roof = true
			upper_steep_roof = true
			steep_roof = true
			upper_lower_roof = true
			attic_roof = true
			planks_upper_lower_roof = true
			roof = true
			planks_attic_roof = true
			planks_top_roof = true
			planks_steep_roof = true
			planks_lower_roof = true

		[entries.wood_type.absentbydesign]
			wall_stripped_log = true
			wall_log = true
			fence_log = true
			wall_planks = true

		[entries.wood_type.mcwfurnitures]
			stripped_glass_table = true
			stripped_desk = true
			end_table = true
			stool_chair = true
			stripped_lower_triple_drawer = true
			stripped_drawer_counter = true
			bookshelf_drawer = true
			double_drawer = true
			stripped_coffee_table = true
			stripped_counter = true
			stripped_striped_chair = true
			covered_desk = true
			stripped_stool_chair = true
			stripped_modern_wardrobe = true
			cupboard_counter = true
			stripped_covered_desk = true
			coffee_table = true
			glass_table = true
			stripped_cupboard_counter = true
			stripped_triple_drawer = true
			stripped_chair = true
			stripped_double_drawer_counter = true
			stripped_modern_desk = true
			stripped_bookshelf_cupboard = true
			modern_wardrobe = true
			lower_bookshelf_drawer = true
			striped_chair = true
			stripped_large_drawer = true
			wardrobe = true
			modern_desk = true
			stripped_lower_bookshelf_drawer = true
			stripped_end_table = true
			drawer = true
			stripped_bookshelf_drawer = true
			stripped_bookshelf = true
			modern_chair = true
			chair = true
			stripped_table = true
			double_drawer_counter = true
			drawer_counter = true
			counter = true
			stripped_modern_chair = true
			bookshelf_cupboard = true
			table = true
			desk = true
			stripped_double_wardrobe = true
			stripped_double_drawer = true
			triple_drawer = true
			lower_triple_drawer = true
			bookshelf = true
			stripped_wardrobe = true
			large_drawer = true
			double_wardrobe = true
			stripped_drawer = true

		[entries.wood_type.mcwtrpdoors]
			ranch_trapdoor = true
			beach_trapdoor = true
			swamp_trapdoor = true
			glass_trapdoor = true
			blossom_trapdoor = true
			tropical_trapdoor = true
			cottage_trapdoor = true
			paper_trapdoor = true
			bark_trapdoor = true
			classic_trapdoor = true
			bamboo_trapdoor = true
			barn_trapdoor = true
			four_panel_trapdoor = true
			barred_trapdoor = true
			mystic_trapdoor = true
			barrel_trapdoor = true

		[entries.wood_type.mcwwindows]
			louvered_shutter = true
			plank_pane_window = true
			plank_four_window = true
			stripped_log_window2 = true
			log_parapet = true
			window2 = true
			stripped_log_four_window = true
			stripped_log_window = true
			plank_window = true
			plank_window2 = true
			pane_window = true
			stripped_pane_window = true
			four_window = true
			plank_parapet = true
			blinds = true
			window = true
			shutter = true

		[entries.wood_type.mcwdoors]
			japanese2_door = true
			tropical_door = true
			barn_glass_door = true
			four_panel_door = true
			beach_door = true
			waffle_door = true
			japanese_door = true
			stable_door = true
			modern_door = true
			nether_door = true
			stable_head_door = true
			cottage_door = true
			western_door = true
			paper_door = true
			bamboo_door = true
			swamp_door = true
			glass_door = true
			barn_door = true
			mystic_door = true
			bark_glass_door = true
			classic_door = true

		[entries.wood_type.mcwfences]
			highley_gate = true
			picket_fence = true
			stockade_fence = true
			wired_fence = true
			horse_fence = true
			pyramid_gate = true

		[entries.wood_type.mcwbridges]
			bridge_pier = true
			rope_bridge = true
			log_bridge_middle = true
			rope_bridge_stair = true
			log_bridge_stair = true
			rail_bridge = true

		[entries.wood_type.mcwpaths]
			planks_path = true

		[entries.wood_type.mcwlights]
			tiki_torch = true
			soul_tiki_torch = true

		[entries.wood_type.functionalstorage]
			1 = true
			4 = true
			2 = true

